name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Add Docker setup step
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    # Login to Docker Hub (if pushing)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    # Build and push
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: tanvir909/ci_cd_docker_git:latest
    
    # Pull the image (if needed)
    - name: Pull Docker image
      run: docker pull tanvir909/ci_cd_docker_git:latest