name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
      - name: Build docker image
        run: docker build -t tanvir909/ci_cd_docker_git .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to docker hub
        run: docker push tanvir909/ci_cd_docker_git:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      # Pull the image (if needed)
      - name: Pull Docker image
        run: docker pull tanvir909/ci_cd_docker_git:latest
      
      - name: Delete old container
        run: docker rm -f ci_cd_docker_git || true
      
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name ci_cd_docker_git tanvir909/ci_cd_docker_git:latest